pipeline {
    agent any

    stages {
        stage('Example') {
            steps {
                echo 'Build triggered from the Test ENV Jenkinsfile..'
            }
        }
    }
}
