
pipeline {
    agent any

    stages {
        stage('test') {
            steps {

                echo 'Build triggered from the Test ENV Jenkinsfile...'

                }
            }
        }
    }
}
